import lancedb
from lancedb.pydantic import LanceModel, Vector
from datetime import datetime


class ImageRecord(LanceModel):
    vector: Vector(4096)     # The semantic meaning of the description
    filename: str            # The original filename (if available)
    file_hash: str           # The SHA256 hash (acts as unique ID)
    description: str         # The text description generated by the Vision API
    created_at: datetime     # When it was added
    path: str                # Full local path to the image file

